import Head from 'next/head'
import SiteHeader from '@/components/SiteHeader/SiteHeader'

type HomePageProps = {
  toggleTheme?: () => void;
}

export default function Home({ toggleTheme } : HomePageProps) {
  return (
    <>
      <Head>
        <title>Home | ThePixelMe.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SiteHeader toggleTheme={toggleTheme} />

      <main>
      </main>
    </>
  )
}
